import { NextResponse } from "next/server";
import { connectDB } from "@/lib/server/db";
import { requireCapability, requireFirmAdmin } from "@/lib/server/auth";
import { AccessLog, resources } from "@/lib/server/models";
const clean=(body:Record<string,unknown>)=>Object.fromEntries(Object.entries(body).filter(([key])=>!["_id","familyOfficeId","familyId","userId","createdAt","updatedAt","__v"].includes(key)&&!key.startsWith("$")));
async function existing(ctx:RouteContext<"/api/resources/[resource]/[id]">){const{resource,id}=await ctx.params,model=resources[resource as keyof typeof resources];if(!model)throw new Error("NOT_FOUND");await connectDB();const row=await model.findById(id).lean() as Record<string,unknown>|null;if(!row)throw new Error("NOT_FOUND");return{resource,id,model,row}}
export async function GET(_req:Request,ctx:RouteContext<"/api/resources/[resource]/[id]">){try{const data=await existing(ctx);const familyId=String(data.row.familyId||"");const auth=data.resource==="access-logs"?await requireFirmAdmin():await requireCapability(data.resource==="tax-observations"?"view_tax":data.resource==="obligations"?"alerts":"view_sheet",familyId);if(String(data.row.familyOfficeId)!==String(auth.membership.familyOfficeId))throw new Error("FORBIDDEN");return NextResponse.json(data.row)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Failed"},{status:error instanceof Error&&error.message==="UNAUTHENTICATED"?401:error instanceof Error&&error.message==="FORBIDDEN"?403:404})}}
export async function PATCH(req:Request,ctx:RouteContext<"/api/resources/[resource]/[id]">){try{const data=await existing(ctx),familyId=String(data.row.familyId||""),incoming=clean(await req.json());let auth;if(data.resource==="line-items"){auth=await requireCapability(Object.keys(incoming).every(key=>["confirmed","held"].includes(key))?"confirm":"edit_sheet",familyId);if(auth.role==="principal"&&!Object.keys(incoming).every(key=>["confirmed","held"].includes(key)))throw new Error("FORBIDDEN")}else if(data.resource==="obligations"){auth=await requireCapability("alerts",familyId);if(auth.role==="principal"&&!Object.keys(incoming).every(key=>key==="acknowledged"))throw new Error("FORBIDDEN")}else if(data.resource==="tax-observations")auth=await requireCapability("manage_tax",familyId);else auth=await requireCapability("edit_sheet",familyId);if(String(data.row.familyOfficeId)!==String(auth.membership.familyOfficeId))throw new Error("FORBIDDEN");const row=await data.model.findByIdAndUpdate(data.id,{$set:incoming},{new:true,runValidators:true});await AccessLog.create({familyOfficeId:auth.membership.familyOfficeId,familyId,userId:auth.user._id,action:"update",target:`${data.resource}:${data.id}`});return NextResponse.json(row)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Failed"},{status:error instanceof Error&&error.message==="FORBIDDEN"?403:400})}}
export async function DELETE(_req:Request,ctx:RouteContext<"/api/resources/[resource]/[id]">){try{const data=await existing(ctx),familyId=String(data.row.familyId||""),auth=await requireCapability("edit_sheet",familyId);if(String(data.row.familyOfficeId)!==String(auth.membership.familyOfficeId))throw new Error("FORBIDDEN");await data.model.findByIdAndDelete(data.id);await AccessLog.create({familyOfficeId:auth.membership.familyOfficeId,familyId,userId:auth.user._id,action:"delete",target:`${data.resource}:${data.id}`});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Failed"},{status:error instanceof Error&&error.message==="FORBIDDEN"?403:400})}}
