import "server-only";
import { cookies } from "next/headers";
import { createHash, createHmac, randomBytes, scrypt as scryptCb, timingSafeEqual } from "crypto";
import { promisify } from "util";
import { connectDB } from "./db";
import { Membership, Session, User } from "./models";
import { hasCapability, type Capability, type Role } from "@/lib/permissions";
export type { Capability, Role } from "@/lib/permissions";
const scrypt=promisify(scryptCb),cookieName=process.env.SESSION_COOKIE_NAME||"nivesh_session",reauthCookieName=process.env.REAUTH_COOKIE_NAME||"nivesh_recent_auth",hash=(x:string)=>createHash("sha256").update(x).digest("hex"),secret=()=>process.env.SESSION_SECRET||process.env.AUTH_SECRET||process.env.MONGODB_URI||"dev-only-nivesh-secret";
type SessionRow={userId:unknown};type UserRow={_id:unknown;name:unknown;email:unknown;active:unknown};type MembershipRow={familyOfficeId:unknown;familyIds:unknown[];role:string};
function signRecentAuth(userId:string,expires:number){return createHmac("sha256",secret()).update(`${userId}.${expires}`).digest("base64url")}
export async function hashPassword(password:string){const salt=randomBytes(16).toString("hex"),key=await scrypt(password,salt,64)as Buffer;return`${salt}:${key.toString("hex")}`}
export async function verifyPassword(password:string,stored:string){const[salt,hex]=stored.split(":");if(!salt||!hex)return false;const key=await scrypt(password,salt,64)as Buffer,a=Buffer.from(hex,"hex");return a.length===key.length&&timingSafeEqual(a,key)}
export async function createSession(userId:string){await connectDB();const token=randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+7*864e5);await Session.create({tokenHash:hash(token),userId,expiresAt});(await cookies()).set(cookieName,token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",expires:expiresAt})}
export async function destroySession(){const store=await cookies(),token=store.get(cookieName)?.value;if(token){await connectDB();await Session.deleteOne({tokenHash:hash(token)})}store.delete(cookieName);store.delete(reauthCookieName)}
export async function getSession(){const token=(await cookies()).get(cookieName)?.value;if(!token)return null;await connectDB();const session=await Session.findOne({tokenHash:hash(token),expiresAt:{$gt:new Date()}}).lean()as unknown as SessionRow|null;if(!session)return null;const user=await User.findById(session.userId).select("name email active").lean()as unknown as UserRow|null;const memberships=await Membership.find({userId:session.userId}).lean()as unknown as MembershipRow[];return user&&user.active?{user,memberships}:null}
export async function requireMembership(familyId?:string){const session=await getSession();if(!session)throw new Error("UNAUTHENTICATED");const membership=session.memberships.find(m=>familyId?m.familyIds.map(String).includes(familyId):m.familyIds.length>0);if(!membership)throw new Error("FORBIDDEN");return{...session,membership,role:membership.role as Role,familyId:familyId||String(membership.familyIds[0])}}
export async function requireCapability(capability:Capability,familyId?:string){const auth=await requireMembership(familyId);if(!hasCapability(auth.role,capability))throw new Error("FORBIDDEN");return auth}
export async function requireFirmAdmin(){const session=await getSession();if(!session)throw new Error("UNAUTHENTICATED");const membership=session.memberships.find(m=>m.role==="admin");if(!membership)throw new Error("FORBIDDEN");return{...session,membership,role:"admin" as const}}
export async function markReauthenticated(userId:unknown){const expires=Date.now()+10*60*1000,value=`${String(userId)}.${expires}.${signRecentAuth(String(userId),expires)}`;(await cookies()).set(reauthCookieName,value,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",expires:new Date(expires)})}
export async function requireRecentReauth(capability:Capability,familyId?:string){const auth=await requireCapability(capability,familyId),value=(await cookies()).get(reauthCookieName)?.value||"",[userId,expiresRaw,signature]=value.split("."),expires=Number(expiresRaw),expected=userId&&Number.isFinite(expires)?signRecentAuth(userId,expires):"",sig=Buffer.from(signature||""),exp=Buffer.from(expected);if(userId!==String(auth.user._id)||expires<Date.now()||!expected||sig.length!==exp.length||!timingSafeEqual(sig,exp))throw new Error("REAUTH_REQUIRED");return auth}
