import { NextResponse } from "next/server";
import { connectDB } from "@/lib/server/db";
import { requireMembership } from "@/lib/server/auth";
import { AccessLog, Document, Entity, Family, LineItem, Obligation, Snapshot, TaxObservation } from "@/lib/server/models";
const pageModel:Record<string,string>={"balance sheet":"line","documents":"document","email inbox":"document","ai processing":"document","review queue":"line","refresh worklist":"line","tax observations":"tax","alerts & obligations":"obligation","90-day cash forecast":"obligation","snapshots & net worth":"snapshot","client families":"family"};
export async function GET(req:Request){try{const page=new URL(req.url).searchParams.get("page")?.toLowerCase()||"",kind=pageModel[page];if(!kind)return NextResponse.json({error:"This page does not contain addable accounting records"},{status:400});const{membership}=await requireMembership();await connectDB();const familyId=String(membership.familyIds[0]||"");const scope={familyOfficeId:membership.familyOfficeId,familyId};const model=kind==="line"?LineItem:kind==="document"?Document:kind==="tax"?TaxObservation:kind==="obligation"?Obligation:kind==="snapshot"?Snapshot:Family;const rows=await model.find(kind==="family"?{familyOfficeId:membership.familyOfficeId}:scope).sort({createdAt:-1}).limit(500).lean();return NextResponse.json(rows)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Failed"},{status:401})}}
export async function POST(req:Request){try{const body=await req.json(),page=String(body.page||"").toLowerCase(),kind=pageModel[page];if(!kind)return NextResponse.json({error:"Adding records is not available on this page"},{status:400});const{membership,user}=await requireMembership();await connectDB();const familyId=String(membership.familyIds[0]||"");if(!familyId)return NextResponse.json({error:"No family assigned to this account"},{status:400});let entity=await Entity.findOne({familyOfficeId:membership.familyOfficeId,familyId,name:String(body.entity||"Rajiv Malhotra")});if(!entity)entity=await Entity.create({familyOfficeId:membership.familyOfficeId,familyId,name:String(body.entity||"Rajiv Malhotra"),type:"individual",excludeFromConsolidation:false});const base={familyOfficeId:membership.familyOfficeId,familyId},name=String(body.name||"New record"),asAtDate=new Date(body.asAt||Date.now());let row;
if(kind==="document")row=await Document.create({...base,filename:name,mimeType:String(body.mimeType||"application/pdf"),size:Number(body.size||0),source:"upload",status:"needs_confirmation",uploadedBy:user._id});
else if(kind==="line"){let source=await Document.findOne({...base});if(!source)source=await Document.create({...base,filename:"Manual declaration",source:"upload",status:"needs_confirmation",uploadedBy:user._id});const amount=Number(body.amount||0),confidence=Number(body.confidence||100);row=await LineItem.create({...base,entityId:entity._id,category:Number(body.category||1),name,amount,costAmount:Number(body.costAmount||amount),basis:String(body.basis||"declared"),confidence,asAtDate,freshnessState:"fresh",sourceDocumentId:source._id,sourceLocation:"Manual entry",confirmed:false,held:confidence<85||Math.abs(amount)>2500000})}
else if(kind==="tax")row=await TaxObservation.create({...base,severity:String(body.severity||"watch"),title:name,body:String(body.notes||""),ruleCited:String(body.ruleCited||"MANUAL-1"),rulesTableVersion:"v2026.04",valueAtStake:Number(body.amount||0),status:"open"});
else if(kind==="obligation"){let source=await Document.findOne({...base});if(!source)source=await Document.create({...base,filename:"Manual obligation",source:"upload",status:"needs_confirmation",uploadedBy:user._id});row=await Obligation.create({...base,entityId:entity._id,title:name,amount:Number(body.amount||0),dueDate:asAtDate,category:String(body.categoryName||"other"),consequence:String(body.notes||""),sourceDocumentId:source._id,acknowledged:false})}
else if(kind==="snapshot")row=await Snapshot.create({...base,asAtDate,assets:Number(body.assets||0),liabilities:Number(body.liabilities||0),netWorth:Number(body.netWorth||0),basis:"fair_value"});
else if(kind==="family"){if(membership.role!=="admin")return NextResponse.json({error:"Only firm admins can add families"},{status:403});row=await Family.create({familyOfficeId:membership.familyOfficeId,name})}
if(!row)return NextResponse.json({error:"Record type is not supported"},{status:400});await AccessLog.create({...base,userId:user._id,action:"create",target:`${kind}:${String(row._id)}`});return NextResponse.json(row,{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Save failed"},{status:400})}}
