import { NextResponse } from "next/server";
import { requireCapability } from "@/lib/server/auth";
import { connectDB } from "@/lib/server/db";
import { AccessLog, RuleSet } from "@/lib/server/models";
import taxDefaults from "@/data/tax-rules.json";
import freshnessDefaults from "@/data/freshness-rules.json";
const valid=new Set(["tax","freshness"]);
export async function GET(_req:Request,ctx:RouteContext<"/api/rules/[kind]">){try{const{kind}=await ctx.params;if(!valid.has(kind))return NextResponse.json({error:"Unknown rules table"},{status:404});const auth=await requireCapability(kind==="tax"?"view_tax":"view_sheet");await connectDB();const saved=await RuleSet.findOne({familyOfficeId:auth.membership.familyOfficeId,kind}).sort({effectiveDate:-1}).lean();return NextResponse.json(saved||{kind,...(kind==="tax"?{version:taxDefaults.version,effectiveDate:taxDefaults.effectiveDate,rules:taxDefaults.rules}:{version:freshnessDefaults.version,effectiveDate:"2026-08-01",rules:freshnessDefaults.rules})})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Failed"},{status:403})}}
export async function PUT(req:Request,ctx:RouteContext<"/api/rules/[kind]">){try{const{kind}=await ctx.params;if(!valid.has(kind))return NextResponse.json({error:"Unknown rules table"},{status:404});const auth=await requireCapability(kind==="tax"?"manage_tax":"refresh"),body=await req.json(),version=String(body.version||"").trim(),effectiveDate=new Date(body.effectiveDate);if(!version||Number.isNaN(effectiveDate.getTime())||!body.rules||typeof body.rules!=="object")return NextResponse.json({error:"Version, effective date and rules are required"},{status:400});await connectDB();const row=await RuleSet.create({familyOfficeId:auth.membership.familyOfficeId,kind,version,effectiveDate,rules:body.rules,updatedBy:auth.user._id});await AccessLog.create({familyOfficeId:auth.membership.familyOfficeId,familyId:auth.familyId,userId:auth.user._id,action:"update_rules",target:`${kind}:${version}`});return NextResponse.json(row,{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Failed"},{status:403})}}
