"use client";
/* eslint-disable react-hooks/set-state-in-effect -- hydration reads the persisted demo role. */
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { useEffect,useState } from "react";
import { navigation } from "@/lib/navigation";
type Role="operator"|"principal"|"ca"|"admin";
const allowed:Record<Role,string[]>={operator:["/overview","/balance-sheet","/documents","/inbox","/processing","/review","/refresh","/tax","/obligations","/forecast","/snapshots","/delivery"],principal:["/overview","/balance-sheet","/review","/tax","/obligations","/forecast","/snapshots","/delivery"],ca:["/overview","/balance-sheet","/tax","/forecast","/snapshots"],admin:["/families","/users","/permissions","/access-log","/billing","/security"]};
const labels:Record<Role,string>={operator:"Operator",principal:"Principal",ca:"CA / advisor",admin:"Firm admin"};
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname(),router=useRouter();const[open,setOpen]=useState(false),[role,setRole]=useState<Role>("operator");useEffect(()=>{const saved=localStorage.getItem("nivesh-role") as Role|null;if(saved&&allowed[saved])setRole(saved)},[]);function changeRole(next:Role){setRole(next);localStorage.setItem("nivesh-role",next);if(!allowed[next].includes(path))router.push(allowed[next][0])}
 return <div className="shell"><aside className={open?"side open":"side"}><div className="logo"><i>नि</i><div><b>Nivesh</b><span>Family wealth, clearly.</span></div><button onClick={()=>setOpen(false)}>×</button></div><div className="tenant"><small>FAMILY OFFICE</small><button><i>RM</i><span>R. Malhotra Family Office<em>4 client families</em></span><b>⌄</b></button></div><nav>{navigation.map(group=>{const items=group.items.filter(x=>allowed[role].includes(x.href));return items.length?<div className="nav-group" key={group.group}><small>{group.group}</small>{items.map(item=><Link onClick={()=>setOpen(false)} className={path===item.href?"active":""} href={item.href} key={item.href}><i>{item.icon}</i><span>{item.label}</span>{item.badge&&<b>{item.badge}</b>}</Link>)}</div>:null})}</nav><div className="identity"><i>{role==="principal"?"RM":role==="ca"?"PS":role==="admin"?"RO":"AM"}</i><span><b>{role==="principal"?"Rajiv Malhotra":role==="ca"?"Priya Shah":role==="admin"?"Rohan Malhotra":"Arjun Mehta"}</b><small>{labels[role]}</small></span></div></aside>{open&&<button className="scrim" onClick={()=>setOpen(false)} aria-label="Close menu"/>}<main className="workspace"><header><button className="hamb" onClick={()=>setOpen(true)}>☰</button><div><small>CLIENT FAMILY</small><b>The Malhotras</b><span>FY 2026–27</span></div><div className="head-right"><select aria-label="View as role" value={role} onChange={e=>changeRole(e.target.value as Role)}><option value="operator">Operator</option><option value="principal">Principal</option><option value="ca">CA / advisor</option><option value="admin">Firm admin</option></select><button>⌕</button><button>♢<i/></button></div></header><div className="page">{children}</div></main></div>}
