"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { navigation } from "@/lib/navigation";
import type { Role } from "@/lib/permissions";
const allowed:Record<Role,string[]>={operator:["/overview","/balance-sheet","/documents","/inbox","/processing","/review","/refresh","/tax","/obligations","/forecast","/snapshots","/delivery"],principal:["/overview","/balance-sheet","/review","/tax","/obligations","/forecast","/snapshots","/delivery"],ca:["/overview","/balance-sheet","/tax","/forecast","/snapshots"],admin:["/families","/users","/permissions","/access-log","/billing","/security"]};
const labels:Record<Role,string>={operator:"Operator",principal:"Principal",ca:"CA / advisor",admin:"Firm admin"};
export function AppShell({children,role,userName,familyName="Assigned family"}:{children:React.ReactNode;role:Role;userName:string;familyName?:string}){const path=usePathname(),[open,setOpen]=useState(false);return <div className="shell"><aside className={open?"side open":"side"}><div className="logo"><i>नि</i><div><b>Nivesh</b><span>Family wealth, clearly.</span></div><button onClick={()=>setOpen(false)}>×</button></div><div className="tenant"><small>FAMILY OFFICE</small><button><i>FO</i><span>{familyName}<em>Authenticated workspace</em></span></button></div><nav>{navigation.map(group=>{const items=group.items.filter(x=>allowed[role].includes(x.href));return items.length?<div className="nav-group" key={group.group}><small>{group.group}</small>{items.map(item=><Link onClick={()=>setOpen(false)} className={path===item.href?"active":""} href={item.href} key={item.href}><i>{item.icon}</i><span>{item.label}</span>{item.badge&&<b>{item.badge}</b>}</Link>)}</div>:null})}</nav><div className="identity"><i>{userName.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</i><span><b>{userName}</b><small>{labels[role]}</small></span></div></aside>{open&&<button className="scrim" onClick={()=>setOpen(false)} aria-label="Close menu"/>}<main className="workspace"><header><button className="hamb" onClick={()=>setOpen(true)}>☰</button><div><small>CLIENT FAMILY</small><b>{familyName}</b><span>FY 2026–27</span></div><div className="head-right"><span>{labels[role]}</span><button aria-label="Search">⌕</button><button aria-label="Notifications">♢<i/></button></div></header><div className="page">{children}</div></main></div>}
