"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge, Metric, Notice } from "./ui";

type Row=Record<string,unknown>;
type Accounting={familyId:string;accepted:Row[];review:Row[];stale:Row[];obligations:Row[];snapshots:Row[];taxObservations:Row[];totals:{assets:number;liabilities:number;netWorth:number;held:number}};
const money=(value:unknown)=>`₹${Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const date=(value:unknown)=>value?new Date(String(value)).toLocaleDateString("en-IN"):"—";

function Source({row}:{row:Row}){const source=row.source as Row|undefined;return source?<button className="source-link" onClick={()=>window.open(`/api/documents/${String(row.sourceDocumentId)}/content`,"_blank","noopener,noreferrer")}>{String(source.filename)} · {String(row.sourceLocation||"")}</button>:<span>Missing source</span>}
function useAccounting(){const[data,setData]=useState<Accounting|null>(null),[error,setError]=useState("");const load=useCallback(async()=>{const response=await fetch("/api/accounting",{cache:"no-store"}),body=await response.json();if(!response.ok)setError(body.error||"Could not load accounting data");else{setData(body);setError("")}},[]);useEffect(()=>{const timer=setTimeout(()=>{void load()},0);return()=>clearTimeout(timer)},[load]);return{data,error,load}}
function Header({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <div className="page-head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{description}</p></div><div className="head-actions">{children}</div></div>}
function SimpleTable({heads,rows}:{heads:string[];rows:unknown[][]}){return <section className="card"><div className="table-wrap"><table><thead><tr>{heads.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell as React.ReactNode}</td>)}</tr>)}</tbody></table></div></section>}
function Lines({rows}:{rows:Row[]}){return <section className="card"><header className="card-head"><div><h2>Accepted assets and liabilities</h2><span>{rows.length} source-backed lines</span></div></header><SimpleTable heads={["Type","Item / source","Category","Entity","Basis","Cost","Value","Freshness"]} rows={rows.map(row=>[Number(row.category)<=8?"Asset":"Liability",<div className="primary-cell" key="n"><b>{String(row.name)}</b><Source row={row}/></div>,row.categoryName,row.entity,row.basis,money(row.costAmount),money(row.amount),<Badge key="f" tone={row.freshnessState==="fresh"?"green":row.freshnessState==="stale"?"red":"amber"}>{String(row.freshnessState)}</Badge>])}/></section>}

export function LiveAccounting({mode}:{mode:"sheet"|"review"|"refresh"|"obligations"|"forecast"|"snapshots"|"tax"}){
 const{data,error,load}=useAccounting(),[message,setMessage]=useState(""),[now]=useState(()=>Date.now());
 const upcoming=useMemo(()=>{const obligations=data?.obligations||[],end=now+90*86400000;return obligations.filter(row=>{const due=new Date(String(row.dueDate)).getTime();return due>=now-86400000&&due<=end})},[data,now]);
 if(error)return <Notice tone="red" title="Accounting data unavailable">{error}</Notice>;if(!data)return <p>Loading verified accounting records…</p>;
 async function patchLine(id:unknown,body:Row){const response=await fetch(`/api/resources/line-items/${String(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();setMessage(response.ok?"Record updated":result.error||"Update failed");if(response.ok)await load()}
 async function snapshot(){if(!data)return;const response=await fetch("/api/resources/snapshots",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({familyId:data.familyId,asAtDate:new Date().toISOString(),assets:data.totals.assets,liabilities:data.totals.liabilities,netWorth:data.totals.netWorth,basis:"fair_value"})}),result=await response.json();setMessage(response.ok?"Snapshot saved":result.error||"Could not save snapshot");if(response.ok)await load()}

 if(mode==="sheet")return <><Header eyebrow="DATABASE-BACKED TRUE & FAIR STATEMENT" title="Balance sheet" description="Only accepted, source-backed figures are counted."><button className="action secondary" onClick={()=>window.location.assign("/api/exports/pdf")}>Export PDF</button><button className="action secondary" onClick={()=>window.location.assign("/api/exports/xlsx")}>Export Excel</button><button className="action" onClick={snapshot}>Save snapshot</button></Header>{message&&<Notice title="Balance sheet">{message}</Notice>}<Notice title="No double-counting">Entities marked “exclude from consolidation” are excluded from these calculated totals.</Notice><div className="metrics three"><Metric label="ASSETS" value={money(data.totals.assets)} note={`${data.accepted.filter(x=>Number(x.category)<=8).length} accepted lines`}/><Metric label="LIABILITIES" value={money(data.totals.liabilities)} note={`${data.accepted.filter(x=>Number(x.category)>=9).length} accepted lines`}/><Metric label="NET WORTH" value={money(data.totals.netWorth)} note="Assets less liabilities" tone="blue"/></div><Lines rows={data.accepted}/><p className="disclaimer">True and fair statement based on available documents. This is not a legally audited financial statement.</p></>;
 if(mode==="review")return <><Header eyebrow="HUMAN-IN-THE-LOOP" title="Review queue" description="Held figures are excluded until confirmed."/><div className="metrics three"><Metric label="WAITING" value={String(data.review.length)} note="Not counted in sheet"/><Metric label="LOW CONFIDENCE" value={String(data.review.filter(x=>Number(x.confidence)<85).length)} note="Below 85%"/><Metric label="HIGH VALUE" value={String(data.review.filter(x=>Math.abs(Number(x.amount))>2500000).length)} note="Above ₹25 lakh"/></div>{message&&<Notice title="Review">{message}</Notice>}{data.review.length===0?<Notice title="Queue clear">No held figures need confirmation.</Notice>:data.review.map(row=><section className="review-card" key={String(row._id)}><header><div><small>HELD FIGURE</small><h2>{String(row.name)}</h2><Source row={row}/></div><Badge tone={Number(row.confidence)<85?"amber":"green"}>{String(row.confidence)}% confidence</Badge></header><div><p><small>EXTRACTED VALUE</small><strong>{money(row.amount)}</strong></p><Notice tone="amber" title="Why held">{Number(row.confidence)<85?"Extraction confidence is below 85%.":"The value exceeds ₹25 lakh and requires human confirmation."}</Notice></div><footer><button className="action" onClick={()=>patchLine(row._id,{confirmed:true,held:false})}>Confirm figure</button></footer></section>)}</>;
 if(mode==="refresh")return <><Header eyebrow="CALCULATED FRESHNESS" title="Refresh worklist" description="Age is calculated from each line’s as-at date and category rule."/><SimpleTable heads={["Holding","Entity","Category","Updated","Age","Threshold","State","Source"]} rows={data.stale.map(row=>[row.name,row.entity,row.categoryName,date(row.asAtDate),`${row.ageDays} days`,`${row.thresholdDays} days`,<Badge key="b" tone={row.freshnessState==="stale"?"red":"amber"}>{String(row.freshnessState)}</Badge>,<Source key="s" row={row}/>])}/></>;
 if(mode==="obligations")return <><Header eyebrow="DOCUMENT-BACKED OBLIGATIONS" title="Alerts & obligations" description="Dates and amounts stored with their source document."><button className="action secondary" onClick={()=>window.location.assign("/api/obligations/ics")}>Export all .ics</button></Header><SimpleTable heads={["Due","Obligation","Entity","Amount","Status","Source"]} rows={data.obligations.map(row=>[date(row.dueDate),row.title,row.entity,money(row.amount),row.acknowledged?"Acknowledged":"Open",<Source key="s" row={row}/>])}/></>;
 if(mode==="forecast"){const startingCash=data.accepted.filter(row=>Number(row.category)===1).reduce((sum,row)=>sum+Number(row.amount),0),commitments=upcoming.reduce((sum,row)=>sum+Number(row.amount),0),balance=startingCash-commitments,rows=upcoming.map((row,index)=>[date(row.dueDate),row.title,money(row.amount),money(startingCash-upcoming.slice(0,index+1).reduce((sum,item)=>sum+Number(item.amount),0)),<Source key="s" row={row}/>]);return <><Header eyebrow="COMMITTED FLOWS ONLY" title="90-day cash forecast" description="Starts with accepted bank/cash and applies only source-backed obligations."/><div className="metrics three"><Metric label="LIQUID CASH" value={money(startingCash)} note="Accepted category 1 records"/><Metric label="90-DAY COMMITMENTS" value={money(commitments)} note={`${upcoming.length} document-backed flows`}/><Metric label="PROJECTED BALANCE" value={money(balance)} note="No assumed income" tone={balance<0?"red":"blue"}/></div><SimpleTable heads={["Date","Committed flow","Amount","Projected cash","Source"]} rows={rows}/></>}
 if(mode==="snapshots")return <><Header eyebrow="SAVED DATABASE RECORDS" title="Snapshots & net worth" description="Point-in-time totals on a consistent basis."><button className="action" onClick={snapshot}>Save today’s snapshot</button></Header>{message&&<Notice title="Snapshot">{message}</Notice>}<SimpleTable heads={["Date","Assets","Liabilities","Net worth","Basis"]} rows={data.snapshots.map(row=>[date(row.asAtDate),money(row.assets),money(row.liabilities),money(row.netWorth),row.basis])}/></>;
 return <><Header eyebrow="VERSIONED TAX OBSERVATIONS" title="Tax observations" description="Database records with rule citations and mandatory CA confirmation."/><Notice tone="amber" title="Not tax advice">Confirm every observation with a qualified Chartered Accountant before action.</Notice><SimpleTable heads={["Severity","Observation","Rule","Rules version","Value at stake","Status"]} rows={data.taxObservations.map(row=>[row.severity,row.title,row.ruleCited,row.rulesTableVersion,money(row.valueAtStake),row.status])}/></>;
}

export function LiveAccessLog(){const[rows,setRows]=useState<Row[]>([]),[error,setError]=useState("");useEffect(()=>{const timer=setTimeout(()=>{void fetch("/api/resources/access-logs",{cache:"no-store"}).then(async response=>{const data=await response.json();if(response.ok)setRows(data);else setError(data.error)})},0);return()=>clearTimeout(timer)},[]);return <><Header eyebrow="QUERYABLE AUDIT TRAIL" title="Access log" description="Database-backed views, source opens, edits, confirmations and exports."/>{error?<Notice tone="red" title="Access denied">{error}</Notice>:<SimpleTable heads={["When","User","Action","Target","Family"]} rows={rows.map(row=>[date(row.createdAt),String(row.userId),row.action,row.target,String(row.familyId||"Firm")])}/>}</>}
