/* eslint-disable react/jsx-key -- Table assigns stable cell keys at render time. */
import { ActionButton, Badge, Metric, Notice, PageHeader, Toggle } from "./ui";
import { DocumentsWorkspace } from "./documents-workspace";
import { assets, liabilities, obligations, taxFlags } from "@/lib/mock-data";

export type Screen = "overview"|"sheet"|"documents"|"inbox"|"processing"|"review"|"refresh"|"tax"|"obligations"|"forecast"|"snapshots"|"delivery"|"families"|"users"|"permissions"|"access"|"billing"|"security";
const statusTone=(x:string)=>x.includes("Fresh")||x.includes("Processed")?"green":x.includes("Stale")?"red":"amber";
const Table=({heads,rows}:{heads:string[];rows:React.ReactNode[][]})=><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>;
const Section=({title,sub,children}:{title:string;sub?:string;children:React.ReactNode})=><section className="card"><div className="card-head"><h2>{title}</h2>{sub&&<span>{sub}</span>}</div>{children}</section>;

export function ScreenView({screen}:{screen:Screen}){
 if(screen==="overview") return <Overview/>;
 if(screen==="sheet") return <Sheet/>;
 if(screen==="documents") return <Documents/>;
 if(screen==="inbox") return <Inbox/>;
 if(screen==="processing") return <Processing/>;
 if(screen==="review") return <Review/>;
 if(screen==="refresh") return <Refresh/>;
 if(screen==="tax") return <Tax/>;
 if(screen==="obligations") return <Obligations/>;
 if(screen==="forecast") return <Forecast/>;
 if(screen==="snapshots") return <Snapshots/>;
 if(screen==="delivery") return <Delivery/>;
 if(screen==="families") return <Families/>;
 if(screen==="users") return <Users/>;
 if(screen==="permissions") return <Permissions/>;
 if(screen==="access") return <Access/>;
 if(screen==="billing") return <Billing/>;
 return <Security/>;
}

function Overview(){return <><PageHeader eyebrow="MONDAY, 10 AUGUST" title="Good morning, Arjun" description="The Malhotra family’s position, worklist and next obligations."><ActionButton>＋ Add documents</ActionButton></PageHeader><section className="wealth-hero"><div><small>CONSOLIDATED NET WORTH</small><h2>₹32.95 Cr</h2><p>As at 8 August 2026 <Badge tone="green">Mostly fresh</Badge></p></div><div className="hero-change"><b>↑ 3.8%</b><span>since 31 Mar 2026</span></div><svg viewBox="0 0 800 92" preserveAspectRatio="none"><path d="M0 80 C80 72 115 76 165 59S270 66 325 48 420 53 485 31 580 40 640 22 735 25 800 7"/></svg><footer><div><small>TOTAL ASSETS</small><b>₹38.14 Cr</b></div><div><small>TOTAL LIABILITIES</small><b>₹5.19 Cr</b></div><div><small>HELD FOR REVIEW</small><b>₹4.23 Cr</b></div></footer></section><div className="grid two"><Section title="Needs your attention" sub="Operator worklist"><Work icon="✓" title="6 figures need review" note="2 high-value · 4 low confidence"/><Work icon="↻" title="4 holdings need refresh" note="Oldest is 21 months stale"/><Work icon="◷" title="3 obligations due in 30 days" note="₹1.23 Cr committed outflow"/></Section><Section title="Next obligations" sub="Document-extracted"><MiniEvent date="12 AUG" title="HDFC Life renewal" value="₹2.84 L"/><MiniEvent date="15 SEP" title="Advance tax · Q2" value="₹1.12 Cr"/><MiniEvent date="30 SEP" title="Home loan EMI" value="₹3.85 L"/></Section></div><Section title="Portfolio by category" sub="Fair value basis"><div className="allocation">{[["Listed investments","51%","₹19.68 Cr"],["Real estate","30%","₹11.50 Cr"],["Private holdings","15%","₹5.80 Cr"],["Other assets","4%","₹1.16 Cr"]].map(x=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:x[1]}}/></i><em>{x[1]}</em><strong>{x[2]}</strong></div>)}</div></Section></>}
function Work({icon,title,note}:{icon:string;title:string;note:string}){return <div className="work-row"><i>{icon}</i><p><b>{title}</b><span>{note}</span></p><button>›</button></div>}
function MiniEvent({date,title,value}:{date:string;title:string;value:string}){return <div className="mini-event"><time>{date}</time><p><b>{title}</b><span>Rajiv Malhotra · source linked</span></p><strong>{value}</strong></div>}

function Sheet(){return <><PageHeader eyebrow="TRUE & FAIR STATEMENT" title="Balance sheet" description="Assets, liabilities and net worth—every figure dated and traceable."><ActionButton kind="secondary">Export PDF / Excel</ActionButton><ActionButton>Save snapshot</ActionButton></PageHeader><Notice title="No double-counting in consolidated view">Malhotra Ventures is excluded as an entity because Rajiv’s 74% stake is already carried as an asset.</Notice><div className="chips">{["Everything","Rajiv","Anjali","Malhotra HUF","MV Pvt Ltd"].map((x,i)=><button className={i===0?"on":""} key={x}>{x}</button>)}</div><div className="metrics three"><Metric label="ASSETS · FAIR VALUE" value="₹38.14 Cr" note="₹19.42 Cr documented cost"/><Metric label="LIABILITIES" value="₹5.19 Cr" note="4 accepted line items"/><Metric label="NET WORTH" value="₹32.95 Cr" note="Assets less liabilities" tone="blue"/></div><Section title="Assets" sub="9 accepted lines · tap a source to trace"><Table heads={["Asset / source","Category","Entity","Basis","Cost","Fair value"]} rows={assets.map(x=>[<div className="primary-cell" key="a"><b>{x[0]}</b><a>{x[6]}</a></div>,x[1],x[2],<Badge tone={statusTone(x[5])}>{x[5]}</Badge>,x[3],<strong key="v">{x[4]}</strong>])}/></Section><Section title="Liabilities" sub="Outstanding balances"><Table heads={["Liability / source","Category","Entity","Freshness","Outstanding"]} rows={liabilities.map(x=>[<div className="primary-cell" key="l"><b>{x[0]}</b><a>{x[5]}</a></div>,x[1],x[2],<Badge tone={statusTone(x[4])}>{x[4]}</Badge>,<strong key="v">{x[3]}</strong>])}/></Section><p className="disclaimer">True and fair statement based on available documents. This is not a legally audited financial statement.</p></>}

function Documents(){return <><PageHeader eyebrow="SOURCE LIBRARY" title="Documents" description="PDF, image and Excel records received by upload or dedicated email."/><DocumentsWorkspace/><Notice title="Golden rule enforced">No accepted line item can exist without a source document and location.</Notice></>}
function Inbox(){return <><PageHeader eyebrow="DEDICATED INGESTION" title="Email inbox" description="Forward statements to this private address; attachments enter the same reading pipeline."><ActionButton>Copy inbox address</ActionButton></PageHeader><Notice title="The Malhotras’ private intake address">malhotras@inbox.nivesh.app</Notice><div className="metrics three"><Metric label="NEW" value="3" note="Awaiting reader"/><Metric label="PROCESSED THIS MONTH" value="18" note="42 attachments"/><Metric label="FAILED" value="0" note="No delivery failures"/></div><Section title="Recent email" sub="Attachments only; sender and subject retained for audit"><Table heads={["Sender","Subject","Attachments","Family match","Received","Status"]} rows={[["statements@hdfcbank.net","Your July account statement","1 PDF","The Malhotras","Today, 8:31 AM","Queued"],["reports@nsdl.co.in","CAS for July 2026","1 PDF","The Malhotras","9 Aug, 6:12 PM","Processed"],["arjun@rmfamilyoffice.in","Alibaug property records","4 files","The Malhotras","9 Aug, 2:04 PM","Needs review"]].map(x=>[x[0],<b key="s">{x[1]}</b>,x[2],x[3],x[4],<Badge key="b" tone={statusTone(x[5])}>{x[5]}</Badge>])}/></Section></>}
function Processing(){const agents=[["Reader","OCR, tables and source locations","GPT-4.1 mini","Done"],["Sorter","Category, entity and confidence","GPT-5 mini","Done"],["Checker","Accounting consistency and mirrors","GPT-5","Running"],["Date Sentinel","Dates, amounts and consequences","GPT-5 mini","Done"],["Advisor","Rule-cited tax observations","GPT-5","Waiting"]];return <><PageHeader eyebrow="MODEL ORCHESTRATION" title="AI processing" description="A staged pipeline with confidence controls and human escalation—not one black-box prompt."/><div className="metrics three"><Metric label="PAGES PROCESSED" value="184" note="Last 30 days"/><Metric label="MODEL ESCALATION" value="18.4%" note="Healthy · alert above 25%" tone="blue"/><Metric label="AVG. DRAFT TIME" value="8m 42s" note="Target under 15 min"/></div><Section title="Current processing run" sub="NSDL_CAS_July26.pdf"><div className="pipeline">{agents.map((x,i)=><div key={x[0]} className={x[3]==="Running"?"running":""}><i>{x[3]==="Done"?"✓":i+1}</i><p><b>{x[0]}</b><span>{x[1]}</span></p><em>{x[2]}</em><Badge tone={x[3]==="Done"?"green":x[3]==="Running"?"amber":"gray"}>{x[3]}</Badge></div>)}</div></Section><Notice title="Materiality guardrail">Any figure below 85% confidence or above ₹25 lakh is held back for a human, even if extraction appears clean.</Notice></>}
function Review(){return <><PageHeader eyebrow="HUMAN-IN-THE-LOOP" title="Review queue" description="Held-back figures are excluded from the accepted statement until a person decides."/><div className="metrics three"><Metric label="WAITING" value="6" note="Not counted in sheet"/><Metric label="LOW CONFIDENCE" value="4" note="Below 85%"/><Metric label="HIGH VALUE" value="2" note="Above ₹25 lakh"/></div>{[["Closing balance · HDFC Bank","₹42,80,900","82%","Couldn’t read the final digit cleanly","HDFC_Statement_Jul26.pdf · p.14"],["Alibaug land · estimated value","₹3.80 Cr","91%","Material value requires confirmation","Savills_Valuation_2026.pdf · p.9"],["Aequitas PMS units","₹1.26 Cr","76%","Scheme name is unclear in scan","PMS_Statement_Q1.pdf · p.2"]].map(x=><section className="review-card" key={x[0]}><header><div><small>HELD FIGURE</small><h2>{x[0]}</h2><a>{x[4]}</a></div><Badge tone={Number(x[2].slice(0,-1))<85?"amber":"green"}>{x[2]} confidence</Badge></header><div><p><small>EXTRACTED VALUE</small><strong>{x[1]}</strong></p><Notice tone="amber" title="Why this is held">{x[3]}</Notice></div><footer><ActionButton kind="secondary">Exclude</ActionButton><ActionButton kind="secondary">Correct figure</ActionButton><ActionButton>Confirm {x[1]}</ActionButton></footer></section>)}</>}
function Refresh(){return <><PageHeader eyebrow="FRESHNESS MODEL" title="Refresh worklist" description="Category-specific thresholds show exactly how old each figure is."><ActionButton kind="secondary">Manage freshness rules</ActionButton></PageHeader><div className="legend"><Badge tone="green">Fresh</Badge> Within threshold <Badge tone="amber">Ageing</Badge> Refresh soon <Badge tone="red">Stale</Badge> Update now</div><Section title="Values needing attention" sub="Oldest first"><Table heads={["Holding","Entity","Category threshold","Last updated","Age","State","Action"]} rows={[["Gold & jewellery","Anjali","12 months","12 Nov 2024","21 months","Stale"],["Malhotra Ventures · 74%","Rajiv","90 days","31 Mar 2026","132 days","Ageing"],["Loan to A. Malhotra","Rajiv","90 days","31 Mar 2026","132 days","Ageing"],["Malabar Hill residence","Joint","12 months","15 Mar 2026","148 days","Ageing"]].map(x=>[<b key="n">{x[0]}</b>,x[1],x[2],x[3],x[4],<Badge key="s" tone={statusTone(x[5])}>{x[5]}</Badge>,<ActionButton key="a" kind="secondary">Request update</ActionButton>])}/></Section></>}

function Tax(){return <><PageHeader eyebrow="DATED RULES TABLE · v2026.04" title="Tax observations" description="Advisory, rule-cited prompts. Every item requires CA confirmation."/><Notice tone="amber" title="Not tax advice">Nivesh does not file returns or execute financial actions. Confirm every observation with a qualified Chartered Accountant.</Notice><div className="grid three">{taxFlags.map(x=><section className="tax-card" key={x[1]}><div><Badge tone={x[0]==="Compliance"?"red":x[0]==="Opportunity"?"green":"amber"}>{x[0]}</Badge><span>{x[4]}</span></div><h2>{x[1]}</h2><p>{x[2]}</p><aside><small>RULE CITED</small><b>{x[3]}</b></aside><footer><ActionButton kind="secondary">Snooze</ActionButton><ActionButton>Send to CA</ActionButton></footer></section>)}</div></>}
function Obligations(){return <><PageHeader eyebrow="DATE SENTINEL" title="Alerts & obligations" description="Due, maturity, renewal and reset dates extracted directly from documents."><ActionButton kind="secondary">Export all .ics</ActionButton></PageHeader><div className="metrics four"><Metric label="OVERDUE" value="1" note="Interest accruing" tone="red"/><Metric label="NEXT 30 DAYS" value="3" note="₹1.23 Cr payable"/><Metric label="NEXT 90 DAYS" value="5" note="₹1.38 Cr payable"/><Metric label="FOUND IN DOCUMENTS" value="5" note="None typed manually"/></div><Section title="Next 90 days" sub="Email · web push · calendar"><div className="timeline">{obligations.map(x=><div key={x[1]}><time>{x[0]}</time><i/><p><b>{x[1]} <Badge>{x[2]}</Badge></b><span>Source: {x[4]} · {x[5]}</span><em>Email 14d + 3d + 1d · Push 3d + due day · .ics</em></p><strong>{x[3]}</strong><ActionButton kind="secondary">Acknowledge</ActionButton></div>)}</div></Section></>}
function Forecast(){return <><PageHeader eyebrow="COMMITTED FLOWS ONLY" title="90-day cash forecast" description="Known EMIs, premiums, taxes, capital calls and contracted inflows—never assumed income."/><div className="metrics four"><Metric label="LIQUID CASH TODAY" value="₹1.76 Cr" note="Bank and deposits"/><Metric label="COMMITTED OUTFLOWS" value="₹1.38 Cr" note="Next 90 days" tone="red"/><Metric label="EXPECTED INFLOWS" value="₹28.00 L" note="Document-backed"/><Metric label="LOWEST POINT" value="₹41.00 L" note="End September" tone="amber"/></div><Section title="Projected cash balance" sub="Comfort floor ₹20 L"><div className="chart"><div className="chart-grid"/><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path className="fill" d="M50 35 L245 80 L440 180 L635 135 L635 205 L50 205Z"/><path d="M50 35 L245 80 L440 180 L635 135"/><circle cx="50" cy="35" r="5"/><circle cx="245" cy="80" r="5"/><circle className="danger" cx="440" cy="180" r="5"/><circle cx="635" cy="135" r="5"/></svg><div><span>Today · ₹1.76 Cr</span><span>August · ₹1.31 Cr</span><span>September · ₹41 L</span><span>October · ₹69 L</span></div></div></Section><Notice tone="red" title="September is tight">Advance tax and a capital call land in the same fortnight. Review the FD maturity, LAS facility, or drawdown date with the family office.</Notice></>}
function Snapshots(){return <><PageHeader eyebrow="CONSISTENT PERIODS" title="Snapshots & net worth" description="Save point-in-time statements and track change on the same valuation basis."><ActionButton>Save today’s snapshot</ActionButton></PageHeader><Section title="Net worth over time" sub="Fair value basis"><div className="chart snapshot"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path className="fill" d="M40 185 C160 165 200 170 270 125 S430 120 500 72 620 65 665 34 V205 H40Z"/><path d="M40 185 C160 165 200 170 270 125 S430 120 500 72 620 65 665 34"/></svg></div></Section><Section title="Saved snapshots"><Table heads={["Date","Net worth","Change","Basis","Saved by"]} rows={[["31 Mar 2026","₹31.74 Cr","—","Consistent · policy v3","Arjun"],["30 Apr 2026","₹31.98 Cr","+₹24 L","Consistent · policy v3","Arjun"],["31 May 2026","₹32.16 Cr","+₹18 L","Consistent · policy v3","Arjun"],["31 Jul 2026","₹32.78 Cr","+₹62 L","Consistent · policy v3","Arjun"],["8 Aug 2026","₹32.95 Cr","+₹17 L","Consistent · policy v3","System"]]}/></Section></>}
function Delivery(){return <><PageHeader eyebrow="DISPATCHER" title="Alert delivery" description="Channels, recipients and lead times by category."/><div className="grid two"><Section title="Channels (v1)">{[["Email","Principals, operator and CA",true],["Web push","Installed PWA only",false],["Calendar invite (.ics)","Google and Outlook",true],["In-app","Always current",true]].map(x=><div className="setting" key={String(x[0])}><p><b>{x[0]}</b><span>{x[1]}</span></p><Toggle initial={Boolean(x[2])}/></div>)}<Notice title="iPhone install required">In a Safari tab, push is never shown as enabled. Use Share → Add to Home Screen first.</Notice></Section><Section title="Lead times by category">{[["Statutory","30, 14, 7, 3, 1 days","High"],["Insurance","21, 7, 3 days + grace","Medium"],["Debt / EMI","7 days + due day","Normal"],["Capital calls / maturity","14 and 3 days","Normal"],["Society and utilities","7 days","Normal"]].map(x=><div className="setting" key={x[0]}><p><b>{x[0]}</b><span>{x[1]}</span></p><Badge tone={x[2]==="High"?"red":x[2]==="Medium"?"amber":"gray"}>{x[2]}</Badge></div>)}</Section></div><Notice tone="amber" title="WhatsApp and SMS are later phases">They are deliberately excluded from v1. Active channels are email, web push, calendar (.ics), and in-app.</Notice></>}

function Families(){return <><PageHeader eyebrow="MULTI-TENANT PORTFOLIO" title="Client families" description="Each household is isolated and visible only to assigned memberships."><ActionButton>＋ Add client family</ActionButton></PageHeader><Section title="R. Malhotra Family Office" sub="4 families"><Table heads={["Family","Status","Entities","Documents","Assigned team","Attention","Action"]} rows={[["The Malhotras","Live","4","16","Arjun · Priya CA","6"],["The Shahs","Processing","2","9","Arjun · Priya CA","3"],["The Kapoors","Live","3","21","Neha · Rao CA","0"],["The Raos","Onboarding","1","0","Arjun","1"]].map(x=>[<b key="n">{x[0]}</b>,<Badge key="s" tone={x[1]==="Live"?"green":"blue"}>{x[1]}</Badge>,x[2],x[3],x[4],x[5],<ActionButton key="a" kind="secondary">Open</ActionButton>])}/></Section><Notice title="Tenant isolation">Every future database query must be scoped by family-office, family assignment, and role membership.</Notice></>}
function Users(){return <><PageHeader eyebrow="PER-FAMILY MEMBERSHIP" title="Users & roles" description="A person may hold different roles for different client families."><ActionButton>＋ Invite user</ActionButton></PageHeader><Section title="Active users"><Table heads={["Name","Role","Email","Assigned families","Last active","Status"]} rows={[["Arjun Mehta","Operator","arjun@rmfamilyoffice.in","4 families","Now","Active"],["Rajiv Malhotra","Principal","rajiv@••••.com","The Malhotras","Today","Active"],["Priya Shah","CA / advisor","priya@••••.co.in","Malhotras, Shahs","Yesterday","Active"],["Rohan Malhotra","Firm admin","rohan@rmfamilyoffice.in","All families","Today","Active"]].map(x=>[<b key="n">{x[0]}</b>,<Badge key="r" tone="blue">{x[1]}</Badge>,x[2],x[3],x[4],<Badge key="s" tone="green">{x[5]}</Badge>])}/></Section></>}
function Permissions(){const rows:[[string,string,string,string,string]]|string[][]=[["Upload / email-ingest documents","✓","—","—","—"],["Work review & refresh queues","✓","—","—","—"],["Build / edit / export sheet","✓","View","View","—"],["Confirm held-back figures","✓","✓","—","—"],["Add gold, art, cash manually","✓","✓","—","—"],["Acknowledge alerts","✓","✓","—","—"],["Tax observations","✓","View","✓","—"],["Manage users, roles, billing","—","—","—","✓"],["Read access logs","—","—","—","✓"]];return <><PageHeader eyebrow="AUTHORISATION SPEC" title="Permission matrix" description="Permissions are evaluated per family. View means read without mutation."/><Section title="Four v1 roles"><Table heads={["Capability","Operator","Principal","CA / advisor","Firm admin"]} rows={rows.map(x=>x.map((v,i)=>i===0?<b key={i}>{v}</b>:v==="✓"?<span className="yes" key={i}>✓</span>:v==="View"?<Badge key={i}>View</Badge>:<span className="no" key={i}>—</span>))}/></Section></>}
function Access(){return <><PageHeader eyebrow="QUERYABLE AUDIT TRAIL" title="Access log" description="Every view, edit, export, confirmation and role change is immutable."/><div className="toolbar"><input placeholder="Search user, family, action or target…"/><button>All roles⌄</button><button>All actions⌄</button></div><Section title="Recent activity"><Table heads={["Who","Role","Action","Target","Family","When"]} rows={[["Arjun Mehta","Operator","Viewed","Balance sheet","Malhotras","Today, 10:04 AM"],["Arjun Mehta","Operator","Confirmed","HDFC balance · ₹42,80,900","Malhotras","Today, 9:56 AM"],["Priya Shah","CA","Viewed","Tax observations","Malhotras","9 Aug, 4:31 PM"],["Arjun Mehta","Operator","Exported","Balance sheet · PDF","Malhotras","9 Aug, 2:18 PM"],["Anjali Malhotra","Principal","Added manual item","Gold declaration","Malhotras","8 Aug, 8:44 PM"]].map(x=>[<b key="n">{x[0]}</b>,<Badge key="r">{x[1]}</Badge>,x[2],x[3],x[4],x[5]])}/></Section></>}
function Billing(){return <><PageHeader eyebrow="FIRM ADMIN ONLY" title="Billing" description="Illustrative commercial surface; no real payment integration yet."/><div className="metrics three"><Metric label="PLAN" value="Family Office" note="Annual billing"/><Metric label="ACTIVE SEATS" value="5" note="2 operator · 1 CA · 1 admin · 1 principal"/><Metric label="CLIENT FAMILIES" value="4" note="2 live · 1 processing · 1 onboarding"/></div><div className="grid two"><Section title="Current usage"><div className="usage"><p><span>Document pages</span><b>1,842 / 5,000</b></p><i><b style={{width:"37%"}}/></i><p><span>Storage</span><b>6.4 GB / 25 GB</b></p><i><b style={{width:"26%"}}/></i><p><span>AI escalation</span><b>18.4% / 25% guardrail</b></p><i><b style={{width:"74%"}}/></i></div></Section><Section title="Billing contact"><div className="billing-contact"><b>Rohan Malhotra</b><span>rohan@rmfamilyoffice.in</span><span>GSTIN: 27AAAAA0000A1Z5</span><ActionButton kind="secondary">Update details</ActionButton></div></Section></div></>}
function Security(){return <><PageHeader eyebrow="STANDING PROMISES" title="Security & data handling" description="The most sensitive dataset a family owns requires product-level safeguards."/><Notice title="India storage · disclosed US AI processing">App, database and documents remain in India. Necessary document content is processed by the direct OpenAI API in the US under DPA and requested Zero Data Retention, with explicit DPDP consent.</Notice><div className="security-grid">{[["⌾","Encrypted everywhere","In transit and at rest."],["⌫","Family-owned data","Permanent deletion on request."],["⊘","Never sold or shared","A product principle, not a toggle."],["⌕","Immutable access logs","Every view and change recorded."],["◎","Explicit consent","Cross-border AI transfer named plainly."],["◇","Re-authentication","Before export or entity changes."],["▦","Tenant isolation","Role and family scoped from query one."]].map(x=><section key={x[1]}><i>{x[0]}</i><p><b>{x[1]}</b><span>{x[2]}</span></p></section>)}</div><Notice tone="red" title="Indemnity disclosure">Nivesh is not an audit, adviser of record, tax filing service, or transaction platform. Every tax observation requires CA confirmation before action.</Notice></>}
