import { NextResponse } from "next/server";
import { connectDB } from "@/lib/server/db";
import { requireCapability, requireFirmAdmin, type Capability } from "@/lib/server/auth";
import { AccessLog, resources } from "@/lib/server/models";
const forbidden=new Set(["familyOfficeId","userId","createdAt","updatedAt","__v"]);
const clean=(body:Record<string,unknown>)=>Object.fromEntries(Object.entries(body).filter(([key])=>!forbidden.has(key)&&!key.startsWith("$")));
const readCapability:Record<string,Capability>={documents:"view_sheet","line-items":"view_sheet",entities:"view_sheet",obligations:"alerts","tax-observations":"view_tax",snapshots:"view_sheet"};
const createCapability:Record<string,Capability>={documents:"upload","line-items":"manual_item",entities:"edit_sheet",obligations:"edit_sheet","tax-observations":"manage_tax",snapshots:"edit_sheet"};
function status(error:unknown){return error instanceof Error&&error.message==="UNAUTHENTICATED"?401:error instanceof Error&&error.message==="FORBIDDEN"?403:400}
export async function GET(req:Request,ctx:RouteContext<"/api/resources/[resource]">){try{const{resource}=await ctx.params,model=resources[resource as keyof typeof resources];if(!model)return NextResponse.json({error:"Unknown resource"},{status:404});const requestedFamily=new URL(req.url).searchParams.get("familyId")||undefined;if(resource==="access-logs"||resource==="families"||resource==="memberships"){const auth=await requireFirmAdmin();await connectDB();const rows=await model.find({familyOfficeId:auth.membership.familyOfficeId}).sort({createdAt:-1}).limit(500).lean();return NextResponse.json(rows)}const capability=readCapability[resource];if(!capability)return NextResponse.json({error:"Resource is not available"},{status:403});const auth=await requireCapability(capability,requestedFamily);await connectDB();const scope={familyOfficeId:auth.membership.familyOfficeId,familyId:auth.familyId};const rows=await model.find(scope).sort({createdAt:-1}).limit(500).lean();await AccessLog.create({...scope,userId:auth.user._id,action:"view",target:resource});return NextResponse.json(rows)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Request failed"},{status:status(error)})}}
export async function POST(req:Request,ctx:RouteContext<"/api/resources/[resource]">){try{const{resource}=await ctx.params,model=resources[resource as keyof typeof resources];if(!model)return NextResponse.json({error:"Unknown resource"},{status:404});const body=clean(await req.json());if(resource==="families"){const auth=await requireFirmAdmin();await connectDB();const row=await model.create({...body,familyOfficeId:auth.membership.familyOfficeId});return NextResponse.json(row,{status:201})}const capability=createCapability[resource];if(!capability)throw new Error("FORBIDDEN");const auth=await requireCapability(capability,String(body.familyId||"")||undefined);await connectDB();body.familyId=auth.familyId;if(resource==="line-items"&&(!body.sourceDocumentId||!body.sourceLocation))return NextResponse.json({error:"Every line item requires a source document and location"},{status:400});if(resource==="line-items")body.held=Number(body.confidence)<85||Math.abs(Number(body.amount))>2500000;const row=await model.create({...body,familyOfficeId:auth.membership.familyOfficeId});await AccessLog.create({familyOfficeId:auth.membership.familyOfficeId,familyId:auth.familyId,userId:auth.user._id,action:"create",target:`${resource}:${row._id}`});return NextResponse.json(row,{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Request failed"},{status:status(error)})}}
